[tool.black]
line-length = 88  # Maximum line length for Black

[tool.isort]
profile = "black"  # Make import sorting compatible with Black

[tool.ruff]
src = ["study_fastapi"]  # Folder with study files
line-length = 88         # Maximum line length for Ruff
fix = true               # Allow Ruff to automatically fix what it can

[tool.ruff.lint]
select = ["E", "F", "I"]      # Enable specific checks (E=errors, F=pyflakes, I=imports)
extend-ignore = []             # Additional rules to ignore, if needed




# ruff check
# ruff check --fix
# ruff check backend/app/models